# Generated by Django 2.2.16 on 2020-09-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_kjhjkhj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtext",
            name="kjhjkhj",
        ),
        migrations.RemoveField(
            model_name="customtext",
            name="title",
        ),
        migrations.AddField(
            model_name="customtext",
            name="titlejhgjhgjfhg",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
