# Generated by Django 2.2.16 on 2020-09-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200915_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='titlejhgjhgjfhg',
            new_name='title',
        ),
    ]
