# Generated by Django 2.2.16 on 2020-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20200915_0551"),
    ]

    operations = [
        migrations.CreateModel(
            name="JHGHJGJ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jhgfhjhkjh", models.BigIntegerField()),
            ],
        ),
    ]
